<?php

namespace Eden\Facebook;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-29 at 02:59:07.
 */
class FactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Factory
     */
    protected $factory;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->factory = eden('facebook');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Eden\Facebook\Factory::auth
     */
    public function testAuth()
    {
        $auth = $this->factory
                ->auth('1234567890', '1234567890', 'http://localhost/');
        $this->assertInstanceOf('Eden\\Facebook\\Auth', $auth);
    }

    /**
     * @covers Eden\Facebook\Factory::feed
     */
    public function testFeed()
    {
        $feed = $this->factory
                ->feed('1234567890');
        $this->assertInstanceOf('Eden\\Facebook\\Feed', $feed);
    }

    /**
     * @covers Eden\Facebook\Factory::graph
     */
    public function testGraph()
    {
        $graph = $this->factory
                ->graph('<ACCESS_TOKEN>');
        $this->assertInstanceOf('Eden\\Facebook\\Graph', $graph);
    }

    /**
     * @covers Eden\Facebook\Factory::fql
     */
    public function testFql()
    {
        $fql = $this->factory
                ->Fql('<ACCESS_TOKEN>');
        $this->assertInstanceOf('Eden\\Facebook\\Fql', $fql);
    }

}
