<?php

namespace Eden\Facebook;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-28 at 08:13:46.
 */
class FeedTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Feed
     */
    protected $pageId = '197474606991151';
    protected $feed;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->feed = eden('facebook')
                ->feed($this->pageId);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Eden\Facebook\Feed::getRss
     */
    public function testGetRss()
    {
        $rssFeed = $this->feed->getRss();
        $this->assertInstanceOf('\SimpleXMLElement', $rssFeed);
    }

    /**
     * @covers Eden\Facebook\Feed::getJson
     */
    public function testGetJson()
    {
        $jsonFeed = $this->feed->getJson();
        $this->assertTrue(is_array($jsonFeed));
    }

}
